services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASSWORD}

  web:
    build:
      context: .
      args:
        APP_NAME: django-crm
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:

# version: '2.0'

# services:
#   db:
#     image: postgres
#     # volumes:
#     #   - /home/db:/var/lib/postgresql/data
#     env_file: 
#       - ./db.env

#   web:
#     build: .
#     image: micropyramid/django-crm:1
#     env_file: 
#       - ./db.env
#     ports:
#       - "8001:8000"
#     depends_on:
#       - db